### ISSUE TITLE
Crz not working in crystal 1.0.0 - functor issue

### ISSUE THREAD

**Issue by kingsleyh** [dhruvrajvanshi/crystalfp#7]
In src/crz/interfaces.cr:3:41

 3 | abstract def map(&block : A -> B) : Functor(B) forall B
                                         ^
Error: can't resolve return type Functor(B)

**Comment by kingsleyh** [comment]
looks like this is the issue:    https://github.com/crystal-lang/crystal/issues/8766

**Comment by dhruvrajvanshi** [comment]
Try with crz: 1.0.1
